name: coppersushi
channels:
  - conda-forge
dependencies:
  - python >= 3.10
  - pytest
  - dash
  - dash-bootstrap-components
  - pypsa
  - gunicorn  # For deploying to Heroku
  - snakeviz  # For visualising cProfile results
